# Site Settings
title: "Resort & Golf Club | Charlottesville VA"
title_separator: "|"
name: "Keswick Hall"
description: "Keswick Hall resort will reopen in late summer 2020. The golf club remains open to members during renovations to preserve and update the historic buildings."
url: https://www.keswick.com
repository: TravelTripperWeb-Sites/keswick-full-site-

# Language Settings
default_lang: 'en'
languages: ['en', 'es']

generate_siteindex: false

# Reading Files
include:
  - _ttio_templates
  - _pages
exclude:
  - _assets
  - _ttio_templates/zom
  - _ttio_templates/bedrock/assets
  - _ttio_templates/bedrock/node_modules
  - _ttio_templates/bedrock/*.md
  - _ttio_templates/bedrock/*.json
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - Makefile
  - media.json
  - models.json
  - node_modules
  - old_media.json
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - sitemap.json
  - tmp
  - vendor
keep_files:
  - assets
  - ttio_templates/bedrock/assets
  - ttio_templates/zom/assets
rsync_copy:
  - _assets
  - _ttio_templates/bedrock/assets
  - _ttio_templates/zom/assets

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  load_paths:
    - _sass
  style: compressed

# Outputting
permalink: pretty
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# data_paginate:
#   per_page: 5
#   data: 'blog'
#   path: 'blog/page:num'
#   pagination_template: 'blog/index.html'
#   sort_field: 'date'
#   sort_reverse: true

page_gen: #
  - data: 'room_categories'
    template: 'room_categories_layout'
    dir: ''
  - data: 'posts'
    template: 'blog_layout'
    dir: 'blog'
  - data: 'gather'
    template: 'gather_layout'
    dir: 'gather'
  - data: 'experience'
    template: 'experience_layout'
    dir: 'experience'
  - data: 'property_highlights'
    template: 'property_highlights_layout'
    dir: 'property-highlights'
  - data: 'plan_your_visit'
    template: 'plan_your_visit_layout'
    dir: 'plan-your-visit'
  - data: 'offers'
    template: 'offer_layout'
    dir: 'offers'
    title_field: name
  - data: 'attractions'
    template: 'attractions_layout'
    dir: 'attractions'
  # - data: 'rooms'
  #   template: 'room_layout'
  #   dir: 'rooms'
  #   title_field: name


plugins_dir:
- _plugins-38
- _plugins
i18n_dir:
- _ttio_templates/bedrock/_locales
- _ttio_templates/bedrock/_themes/none/_locales
- _ttio_templates/conversion-plus/_locales
- _locales
layouts_dir:
- _ttio_templates/bedrock/_layouts
- _ttio_templates/bedrock/_themes/none/_layouts
- _ttio_templates/conversion-plus/_layouts
- _layouts
data_dir:
- _ttio_templates/bedrock/_data
- _ttio_templates/bedrock/_themes/none/_data
- _ttio_templates/conversion-plus/_data
- _data
includes_dir:
- _includes
- _ttio_templates/conversion-plus/_includes
- _ttio_templates/bedrock/_themes/none/_includes
- _ttio_templates/bedrock/_includes
