---
latitude: 40.750613
longitude: -73.977095
map_zoom: 15
name: Topping Rose House
email: support@traveltripper.com
phone_number: 434-979-3440
address:
  street1: 701 Club Drive  /  Keswick, Virginia
  state: NY
  city: New York
  zip_code: 22947
default_currency: USD
default_timezone: America/New_York
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  logo_secondary:
    type: image
  logo_mobile:
    type: image
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  google_location:
    type: location
  map_zoom:
    type: integer
  latitude:
    type: float
  longitude:
    type: float
get_directions: https://goo.gl/maps/qLhg6kYXBTKJtqxUA
logo:
  name: topping-rose-white
  content_type: image/png
  date_added: 2021-03-01-061830
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,f_auto,g_faces,h_140,q_auto,w_140/v1614597511/tuxhfxsmwplnncgbsler.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,f_auto,h_300,q_auto,w_300/v1614597511/tuxhfxsmwplnncgbsler.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,f_auto,h_768,q_auto,w_768/v1614597511/tuxhfxsmwplnncgbsler.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,f_auto,h_992,q_auto,w_992/v1614597511/tuxhfxsmwplnncgbsler.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,f_auto,h_1200,q_auto,w_1200/v1614597511/tuxhfxsmwplnncgbsler.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,f_auto,h_1920,q_auto,w_1920/v1614597511/tuxhfxsmwplnncgbsler.png"
  url: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,f_auto,h_2500,q_auto,w_2500/v1614597511/tuxhfxsmwplnncgbsler.png"
  width: 184
  height: 260
  format: png
  url_raw: "//res.cloudinary.com/traveltripperweb/image/upload/v1614597511/tuxhfxsmwplnncgbsler.png"
  resource_type: image
  size: 10009
  git_file_name: _assets/image_data/topping-rose-white.png.json
  path: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,f_auto,h_2500,q_auto,w_2500/v1614597511/tuxhfxsmwplnncgbsler.png"
  file_size: 
  alt: Topping Rose House
  caption: ''
  description: ''
logo_secondary:
  name: Kewsick-Logo-light
  content_type: image/svg+xml
  date_added: 2020-03-05-053628
  format: 
  url: "//res.cloudinary.com/traveltripperweb/raw/upload/v1583404588/sgaxwjebjsh2wmzsmutr.svg"
  url_raw: "//res.cloudinary.com/traveltripperweb/raw/upload/v1583404588/sgaxwjebjsh2wmzsmutr.svg"
  resource_type: raw
  size: 12405
  path: "//res.cloudinary.com/traveltripperweb/raw/upload/v1583404588/sgaxwjebjsh2wmzsmutr.svg"
  file_size: 
  alt: Keswick Hall
  caption: ''
  description: ''
logo_mobile:
  name: Keswick-horizontal-Logo-white
  content_type: image/svg+xml
  date_added: 2020-03-05-062312
  format: 
  url: "//res.cloudinary.com/traveltripperweb/raw/upload/v1583407392/uph0gzbqs7ft4uwsskjp.svg"
  url_raw: "//res.cloudinary.com/traveltripperweb/raw/upload/v1583407392/uph0gzbqs7ft4uwsskjp.svg"
  resource_type: raw
  size: 3718
  path: "//res.cloudinary.com/traveltripperweb/raw/upload/v1583407392/uph0gzbqs7ft4uwsskjp.svg"
  file_size: 
  alt: Keswick Hall
  caption: ''
  description: ''
