items:
  - id: __environment_settings__
  - id: __redirects__
  - id: hotel_settings
  - id: analytics
  - id: cp
    label: Conversion Plus
    items:
      - id: booking_widget
      - id: brg_configuration
        label: Tonights Rate Banner
      #- id: conversion_plus_banner
      #  label: Conversion Plus Banner      
  - id: forms
  - id: seo
  - id: social
  - id: verification
  